/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.zc.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.zc.model.PrivilegeModel;
import com.zc.model.ResultEntity;

import javax.validation.Valid;
import java.util.List;

@Api(value = "privileges", description = "the privileges API")
public interface PrivilegesApi {

	 @ApiOperation(value = "给用户添加索引信息编辑权限", nickname = "addPrivilege", notes = "", response = ResultEntity.class, tags={ "privilege", })
	    @ApiResponses(value = { 
	        @ApiResponse(code = 200, message = "successful operation", response = ResultEntity.class),
	        @ApiResponse(code = 405, message = "Invalid input") })
	    @RequestMapping(value = "/privileges/{cluster-id}",
	        produces = { "application/json" }, 
	        consumes = { "application/json" },
	        method = RequestMethod.POST)
	    ResponseEntity<ResultEntity> addPrivilege(@ApiParam(value = "集群唯一标识",required=true) @PathVariable("cluster-id") String clusterId,@ApiParam(value = "集群实体" ,required=true )  @Valid @RequestBody List<PrivilegeModel> body);


	    @ApiOperation(value = "删除权限", nickname = "deletePrivilege", notes = "", response = ResultEntity.class, tags={ "privilege", })
	    @ApiResponses(value = { 
	        @ApiResponse(code = 200, message = "successful operation", response = ResultEntity.class),
	        @ApiResponse(code = 405, message = "Invalid input") })
	    @RequestMapping(value = "/privileges/{cluster-id}",
	        produces = { "application/json" }, 
	        consumes = { "application/json" },
	        method = RequestMethod.DELETE)
	    ResponseEntity<ResultEntity> deletePrivilege(@ApiParam(value = "集群唯一标识",required=true) @PathVariable("cluster-id") String clusterId,@ApiParam(value = "集群实体" ,required=true )  @Valid @RequestBody List<PrivilegeModel> body);


    @ApiOperation(value = "获取所有权限信息", nickname = "getPrivilegeList", notes = "", response = PrivilegeModel.class, responseContainer = "List", tags={ "privilege", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = PrivilegeModel.class, responseContainer = "List"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/privileges/{cluster-id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<PrivilegeModel>> getPrivilegeList(@ApiParam(value = "集群唯一标识",required=true) @PathVariable("cluster-id") String clusterId);

}
